//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.20 at 11:45:05 AM CEST 
//


package com.producingwebservice.soap.soapmodel.lanemodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.producingwebservice.soap.soapmodel.lanemodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.producingwebservice.soap.soapmodel.lanemodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReadLaneRequest }
     * 
     */
    public ReadLaneRequest createReadLaneRequest() {
        return new ReadLaneRequest();
    }

    /**
     * Create an instance of {@link ReadLaneResponse }
     * 
     */
    public ReadLaneResponse createReadLaneResponse() {
        return new ReadLaneResponse();
    }

    /**
     * Create an instance of {@link LaneSoap }
     * 
     */
    public LaneSoap createLaneSoap() {
        return new LaneSoap();
    }

}
